### ISSUE TITLE
A little sparse on documentation eg in README

### ISSUE THREAD

**Issue by themusicgod1** [aio-libs/async_lru#28]
What kinds of things can this cache be used for?
What should the example be expected to *do*?
What is the rationale behind the example?
etc

For example: how does this sound?

 Asynchronous "Least Recently Used"-style cache for input/output use.
 For example, using async-lru with resources available via HTTP allows for
 those resources to be downloaded, cached and returned when remote HTTP
 resources are actually available.  async-lru helps programmers build a higher
 level view of these network calls for APIs to be built on.

See example below:

( The webpage at "https://www.python.org/" is downloaded (via HTTP) and stored 6 times.
It is both run once, as a proof that you can control how many times a resource or set of resources are requested, or as many times as needed within a loop using run_until_complete() )

**Comment by hellysmile** [comment]
Thanks for the feedback, are You interested to create a pull request to enrich the documentatio? Any help is aperciated

**Comment by hellysmile** [comment]
Here is another fix for this issue https://github.com/aio-libs/async_lru/pull/33
