### ISSUE TITLE
alru_cache caches the created Task objects

### ISSUE THREAD

**Issue by gjcarneiro** [aio-libs/async_lru#82]
This test program prints `Tasks:  101`:

```python
import asyncio
from async_lru import alru_cache
import random


@alru_cache(maxsize=100)
async def cached_test(arg):
    return arg


async def main():
    while True:
        arg = random.random()
        value = await cached_test(arg)
        assert arg == value
        print("Tasks: ", len(asyncio.Task.all_tasks()))


asyncio.run(main())
```

While it's OK to wrap the coroutine in a Task, it is not OK to keep the Task around.  It should be keeping only the arg and result in its cache, not the Task.

**Comment by asvetlov** [comment]
Why not?
What is your problem?

**Comment by gjcarneiro** [comment]
If I have `maxsize=16384`, I end up with 16k tasks, each task references a coroutine, which references more objects.

The end result is lots of Python objects alive.  Tracked by the GC.  When you have lots of Python objects tracked by the GC, then GC collections become slow: after a few days of my program running, GC pauses take more than half a second each.  For real-time things, half a second is way too long.

Frankly, I don't know how to fix this code.  I ended up just copy-pasting Python's `functools.lru_cache` and modifying it to become async aware.  It's not hard.

But it took me a long time to track down the memory leak due to this alru_cache, so I ask that it either be fixed or at least documented, so that the next person to use this module is aware of this problem.

**Comment by asvetlov** [comment]
`maxsize=16384` is quite huge :)
Well, I'm convinced that the proposal makes sense.
Unfortunately, I have no time to make it done but will happy to review a pull request.

**Comment by hellysmile** [comment]
Hello there!
Keep tasks is a feature for graceful closing
https://github.com/aio-libs/async_lru/blob/master/async_lru.py#L77

**Comment by hellysmile** [comment]
hmmm, they should be released right over here
https://github.com/aio-libs/async_lru/blob/master/async_lru.py#L229

**Comment by hellysmile** [comment]
Hmm there might be a small `"typo"`

https://github.com/aio-libs/async_lru/pull/83
Give me some time to debug, that PR fixes Your issue

**Comment by gjcarneiro** [comment]
I don't understand what you mean by graceful closing.

> hmmm, they should be released right over here

Clearly they're not.  The tasks are kept alive.  Not even a `gc.collect()` cleans them.

**Comment by gjcarneiro** [comment]
Ah, cool, #83 seems to fix it!

**Comment by hellysmile** [comment]
Take a look on pr please

**Comment by hellysmile** [comment]
Should be fixed by https://pypi.org/project/async_lru/ 1.0.2 release

**Comment by hellysmile** [comment]
@gjcarneiro thanks for the reporting!
